/**
 * 天賦效果行英→繁片語（長度長者先替換，避免子字串被先吃掉）。
 * 與 talentEffectLineZh.ts 內建 PHRASES 合併後一併排序。
 */
export const TALENT_EFFECT_LINE_PHRASES_EXTRA: Array<[string, string]> = [
  ['Critical Strike Rating against Frostbitten enemies', '對霜凍敵人之暴擊值'],
  ['Critical Strike Damage against Frostbitten enemies', '對霜凍敵人之暴擊傷害'],
  ['Critical Strike Damage against enemies affected by Ailments', '對受異常狀態敵人之暴擊傷害'],
  ['Critical Strike Damage Mitigation against Blinded enemies', '對致盲敵人之暴擊傷害減免'],
  ['Minion Critical Strike Damage against enemies affected by Ailments', '召喚物對受異常狀態敵人之暴擊傷害'],
  ['Spirit Magus Ultimate Damage and Ailment Damage dealt by Ultimate.', '魔導精靈終極技能傷害與終極技能造成的異常傷害'],
  ['Spirit Magus Ultimate Cooldown Recovery Speed', '魔導精靈終極技能冷卻回復速度'],
  ['Spirit Magus Skill Damage', '魔導精靈技能傷害'],
  ['additional damage against Frozen enemies', '對冰封敵人之額外傷害'],
  ['additional damage against Low Life enemies', '對低血敵人之額外傷害'],
  ['additional damage against Cursed enemies', '對受詛咒敵人之額外傷害'],
  ['additional damage taken by enemies in Proximity', '近距離內敵人所受額外傷害'],
  ['additional damage when having both Sealed Mana and Life', '同時擁有封魔與生命時之額外傷害'],
  ['additional damage for 4s after using Mobility Skills', '使用位移技能後 4 秒內額外傷害'],
  ['additional Sentry Damage if Sentry Skill is not used in the last 1 s', '過去 1 秒未使用哨衛技能時哨衛額外傷害'],
  ['additional Base Damage for Two-Handed Weapons', '雙手武器額外基礎傷害'],
  ['additional Max Damage for Minions', '召喚物額外最大傷害'],
  ['additional Max Damage', '額外最大傷害'],
  ['additional Trauma Damage dealt by Critical Strikes', '暴擊造成之額外創傷傷害'],
  ['additional Evasion on Spell Damage', '受法術傷害時額外閃避'],
  ['additional Elemental Damage taken', '所受額外元素傷害'],
  ['additional Physical Damage taken', '所受額外物理傷害'],
  ['additional Deterioration Duration', '額外惡化持續時間'],
  ['additional Energy Shield Charge Interval', '額外能量護盾充能間隔'],
  ['additional Life Regain Interval', '額外生命回復間隔'],
  ['additional Regain Interval', '額外回復間隔'],
  ['additional Sentry Start Time', '額外哨衛啟動時間'],
  ['additional Spirit Magus Skill Damage', '額外魔導精靈技能傷害'],
  ['additional damage taken', '所受額外傷害'],
  ['additional damage applied to Life', '套用於生命之額外傷害'],
  ['additional Fire Damage', '額外火焰傷害'],
  ['additional Deterioration Damage', '額外惡化傷害'],
  ['additional Physical Damage while having Fervor', '擁有狂熱時額外物理傷害'],
  ['additional Minion Damage if a Synthetic Troop Skill has been cast recently', '近期施放合成部隊技能時召喚物額外傷害'],
  ['additional Max Energy Shield if you have triggered Shield Regain in the last 8s', '過去 8 秒內觸發護盾回復時額外最大能量護盾'],
  ['additional Attack Damage if you have used a Warcry Skill in the last 8s', '過去 8 秒內使用戰吼技能時額外攻擊傷害'],
  ['additional Attack Damage when holding a One-Handed Weapon', '持單手武器時額外攻擊傷害'],
  ['additional Sentry Damage', '額外哨衛傷害'],
  ['additional Spell Damage', '額外法術傷害'],
  ['additional damage if you have lost Life recently', '近期失去生命時額外傷害'],
  ['additional damage if you have taken damage recently', '近期受傷時額外傷害'],
  ['additional Attack Speed for each time you have Regained in the last 8s. Stacks up to 4 time(s)', '過去 8 秒內每次回復可額外攻擊速度，最多疊加 4 次'],
  ['additional Cast Speed for each time you have Regained in the last 8s. Stacks up to 4 time(s)', '過去 8 秒內每次回復可額外施法速度，最多疊加 4 次'],
  ['additional Attack Speed when performing Multistrikes', '多重打擊時額外攻擊速度'],
  ['additional Attack Speed if you have dealt a Critical Strike recently', '近期造成暴擊時額外攻擊速度'],
  ['additional Cast Speed if you have dealt a Critical Strike recently', '近期造成暴擊時額外施法速度'],
  ['additional Attack Speed while Dual Wielding', '雙持時額外攻擊速度'],
  ['additional Attack Damage for each unique type of weapon equipped while Dual Wielding', '雙持且裝備多種武器類型時每件額外攻擊傷害'],
  ['chance to gain a stack of Focus Blessing upon inflicting damage to a Frostbitten enemy. Interval: 0.1s', '對霜凍敵人造成傷害時獲得專注祝福層數，間隔：0.1 秒'],
  ['chance to gain Blur when inflicting crowd control effects', '造成控場效果時獲得飄忽的機率'],
  ['chance to gain Blur on defeat', '擊敗時獲得飄忽的機率'],
  ['chance to gain Blur when Reaping', '收割時獲得飄忽的機率'],
  ['chance to gain 1 stacks of Tenacity Blessing when taking damage. Interval: 1 s', '受傷時獲得 1 層堅韌祝福，間隔：1 秒'],
  ['chance to gain Agility Blessing on Critical Strike', '暴擊時獲得敏捷祝福的機率'],
  ['chance to gain Attack Aggression on defeat', '擊敗時獲得攻擊侵略的機率'],
  ['chance to Blind the target on hit', '命中時致盲目標的機率'],
  ['chance to Mark the enemy on Critical Strike', '暴擊時標記敵人的機率'],
  ['chance to Multistrike', '多重打擊機率'],
  ['chance to inflict Slow on hit', '命中時造成緩速的機率'],
  ['chance to avoid Elemental Ailments', '避免元素異常狀態的機率'],
  ['chance to avoid damage', '避免傷害的機率'],
  ['chance to Ignite targets', '點燃目標的機率'],
  ['chance to inflict Damaging Ailments', '造成傷害類異常的機率'],
  ['chance to inflict Trauma', '造成創傷的機率'],
  ['chance for Minions to inflict Damaging Ailments', '召喚物造成傷害類異常的機率'],
  ['chance for Minions to inflict Trauma', '召喚物造成創傷的機率'],
  ['chance for Spirit Magi to use an Enhanced Skill', '魔導精靈使用強化技能的機率'],
  ['chance for Synthetic Troop Minions to deal Double Damage', '合成部隊召喚物造成雙倍傷害的機率'],
  ['Attack Damage while Tenacity Blessing is active', '堅韌祝福生效時攻擊傷害'],
  ['Movement Speed while Blur is active', '飄忽生效時移動速度'],
  ['Spell Damage when having Focus Blessing', '擁有專注祝福時法術傷害'],
  ['damage while Focus Blessing is active', '專注祝福生效時傷害'],
  ['Attack and Cast Speed when having Agility Blessing', '擁有敏捷祝福時攻擊與施法速度'],
  ['Attack and Cast Speed when channeled stacks have not reached cap', '引導層數未達上限時攻擊與施法速度'],
  ['Attack and Cast Speed when at Full Mana', '滿魔時攻擊與施法速度'],
  ['Attack Damage when holding a Two-Handed Weapon', '持雙手武器時攻擊傷害'],
  ['Attack Damage when holding a One-Handed Weapon', '持單手武器時攻擊傷害'],
  ['Attack Damage while Dual Wielding', '雙持時攻擊傷害'],
  ['Attack Damage if you have Regained in the last 8s', '過去 8 秒內曾回復時攻擊傷害'],
  ['Spell Damage when holding a Shield', '持盾時法術傷害'],
  ['Spell Damage if you have Regained in the last 8s', '過去 8 秒內曾回復時法術傷害'],
  ['Spell Damage at Low Mana', '低魔時法術傷害'],
  ['Spell Critical Strike Damage per stack of Focus Blessing owned', '每層專注祝福之法術暴擊傷害'],
  ['Projectile Critical Strike Damage', '投射物暴擊傷害'],
  ['Projectile Critical Strike Rating', '投射物暴擊值'],
  ['Sentry Skill Critical Strike Damage', '哨衛技能暴擊傷害'],
  ['Sentry Skill Critical Strike Rating', '哨衛技能暴擊值'],
  ['Sentry Skill cast frequency', '哨衛技能施放頻率'],
  ['Sentry Projectile Speed', '哨衛投射物速度'],
  ['Sentry Skill Area', '哨衛技能範圍'],
  ['Sentry Duration', '哨衛持續時間'],
  ['Sentry Damage when moving', '移動時哨衛傷害'],
  ['Minion Damage if a Synthetic Troop Skill has been cast recently', '近期施放合成部隊技能時召喚物傷害'],
  ['Minion Attack and Cast Speed for every 2 Command owned', '每 2 點統御之召喚物攻擊與施法速度'],
  ['Minion Fire Damage per 12 Strength', '每 12 力量之召喚物火焰傷害'],
  ['Minion Fire Penetration against Ignited enemies', '對燃燒敵人之召喚物火焰穿透'],
  ['Physical Damage for Minions', '召喚物物理傷害'],
  ['Ignite chance for Minions', '召喚物點燃機率'],
  ['Minion Skill Area', '召喚物技能範圍'],
  ['Minion Multistrike chance', '召喚物多重打擊機率'],
  ['Minion Life Regeneration Speed', '召喚物生命再生速度'],
  ['Minion Max Life', '召喚物最大生命'],
  ['Minion Affliction Effect', '召喚物侵蝕效果'],
  ['Cold Penetration for Minions', '召喚物冰冷穿透'],
  ['Lightning Penetration for Minions', '召喚物閃電穿透'],
  ['Armor DMG Mitigation Penetration for Minions', '召喚物護甲傷害減免穿透'],
  ['Affliction inflicted per second by Minions', '召喚物每秒施加侵蝕'],
  ['Fire Penetration against Ignited enemies', '對燃燒敵人之火焰穿透'],
  ['Cold Penetration', '冰冷穿透'],
  ['Lightning Penetration', '閃電穿透'],
  ['Fire Damage Over Time', '火焰持續傷害'],
  ['Damage Over Time', '持續傷害'],
  ['Mana Regeneration Speed', '魔力再生速度'],
  ['Cooldown Recovery Speed', '冷卻回復速度'],
  ['Energy Shield gained from Shield', '來自盾牌的能量護盾獲取'],
  ['Energy Shield Charge Speed', '能量護盾充能速度'],
  ['Max Energy Shield per 5 Intelligence', '每 5 智慧之最大能量護盾'],
  ['Max Life per 5 Strength', '每 5 力量之最大生命'],
  ['Mana per 6 Intelligence', '每 6 智慧之魔力'],
  ['Armor for every 24 Strength', '每 24 力量之護甲'],
  ['Attack and Cast Speed per 40 Dexterity', '每 40 敏捷之攻擊與施法速度'],
  ['Evasion per 24 Dexterity', '每 24 敏捷之閃避'],
  ['Fire Damage per 12 Strength', '每 12 力量之火焰傷害'],
  ['Movement Speed per 10 Fervor Rating', '每 10 狂熱值之移動速度'],
  ['Restoration Skill Effect for every 2% of Life lost', '每失去 2% 生命之復原技能效果'],
  ['Life Regeneration Speed per stack of Tenacity Blessing owned', '每層堅韌祝福之生命再生速度'],
  ['Armor per stack of Tenacity Blessing owned', '每層堅韌祝福之護甲'],
  ['Evasion per stack of Agility Blessing owned', '每層敏捷祝福之閃避'],
  ['Block Ratio when holding a Shield', '持盾時格擋比例'],
  ['Attack Block Chance when holding a Shield', '持盾時攻擊格擋機率'],
  ['Attack and Cast Speed when holding a Shield', '持盾時攻擊與施法速度'],
  ['Cast Speed when Focus Blessing is active', '專注祝福生效時施法速度'],
  ['Defense when holding a Shield', '持盾時防禦值'],
  ['Defense from Shield', '來自盾牌之防禦值'],
  ['Defense gained from Chest Armor', '來自胸甲之防禦值'],
  ['Skill Area if Main Skill is not used in the last 2 s', '過去 2 秒未使用主技能時技能範圍'],
  ['Curse Skill Area', '詛咒技能範圍'],
  ['Curse Effect', '詛咒效果'],
  ['Warcry Effect', '戰吼效果'],
  ['Aura Effect', '光環效果'],
  ['Focus Speed', '專注速度'],
  ['Terra Skill Damage', '泰拉技能傷害'],
  ['Trauma Damage', '創傷傷害'],
  ['Ailment Damage', '異常傷害'],
  ['Area Damage', '範圍傷害'],
  ['Affliction Effect', '侵蝕效果'],
  ['Affliction inflicted per second', '每秒施加侵蝕'],
  ['Reaping Duration', '收割持續時間'],
  ['Reaping Recovery Speed', '收割回復速度'],
  ['Trauma Reaping Duration', '創傷收割持續時間'],
  ['Tangle Duration', '纏繞持續時間'],
  ['Skill Effect Duration', '技能效果持續時間'],
  ['Sealed Mana Compensation', '封魔補償'],
  ['Sealed Mana Compensation for Spirit Magus Skills', '魔導精靈技能之封魔補償'],
  ['Origin of Spirit Magus effect', '魔導精靈本源效果'],
  ['Injury Buffer', '傷害緩衝'],
  ['Knockback distance', '擊退距離'],
  ['Knockback Chance', '擊退機率'],
  ['Steep Strike chance.', '斜擊機率'],
  ['Terra Charge Recovery Speed', '泰拉蓄能回復速度'],
  ['Demolisher Charge Restoration Speed', '破壞者蓄能回復速度'],
  ['Wilt chance', '枯萎機率'],
  [' Wilt  Duration', ' 枯萎 持續時間'],
  ['Wilt Duration', '枯萎持續時間'],
  ['Deterioration Chance', '惡化機率'],
  ['Deterioration Damage', '惡化傷害'],
  ['Deterioration Duration', '惡化持續時間'],
  ['Erosion Resistance', '腐蝕抗性'],
  ['Fire Resistance', '火焰抗性'],
  ['Cold Resistance', '冰冷抗性'],
  ['Lightning Resistance', '閃電抗性'],
  ['Max Fire Resistance', '最大火焰抗性'],
  ['Fervor effect', '狂熱效果'],
  ['Mark effect', '標記效果'],
  ['Numbed Effect', '麻木效果'],
  ['Blur effect', '飄忽效果'],
  ['Blur Effect', '飄忽效果'],
  ['Crowd Control Effects', '控場效果'],
  ['Horizontal Projectile Penetration(s)', '水平投射物穿透次數'],
  ['to Max Frostbite Rating', '最大霜凍值'],
  ['to Max Spirit Magi In Map', '地圖內最大魔導精靈數'],
  ['to Parabolic Projectile Splits quantity', '拋物線投射物分裂數量'],
  ['to the minimum number of enemies affected by Warcry', '戰吼影響敵人最小數量'],
  ['to the Max Life and Energy Shield thresholds for inflicting Numbed', '造成麻木之最大生命與能量護盾門檻'],
  ['to All Skills\' Levels', '全技能等級'],
  ['Sentry quantity that can be deployed at a time', '同時可部署哨衛數量'],
  ['damage dealt when holding a Shield', '持盾時造成傷害'],
  ['damage dealt to Nearby enemies', '對附近敵人造成傷害'],
  ['damage to Distant enemies', '對遠方敵人傷害'],
  ['damage against Cursed enemies', '對受詛咒敵人傷害'],
  ['damage if you have Blocked recently', '近期曾格擋時傷害'],
  ['damage if you have defeated an enemy recently', '近期擊敗敵人時傷害'],
  ['damage if you have taken damage recently', '近期受傷時傷害'],
  ['damage if you have Regained in the last 8s', '過去 8 秒內曾回復時傷害'],
  ['damage for Channeled Skills', '引導技能傷害'],
  ['damage for Triggered Skills', '觸發技能傷害'],
  ['damage for every +1 additional Max Channeled Stack(s)', '每 +1 額外最大引導層數之傷害'],
  ['damage while standing still', '靜止時傷害'],
  ['damage and +1% Movement Speed for 4 s on defeat. Stacks up to 8 time(s)', '擊敗時傷害與 +1% 移動速度，持續 4 秒，最多疊加 8 次'],
  ['Projectile Damage against enemies in proximity', '對近距離敵人之投射物傷害'],
  ['inflicted Paralysis Effect when holding a Two-Handed Weapon', '持雙手武器時造成麻痺效果'],
  ['All Resistance when the enemy has max Affliction', '敵人侵蝕層數最大時全抗性'],
  ['of damage is taken from Mana before life', '傷害先由魔力承擔再扣生命'],
  ['of damage taken is transferred to a random Minion', '所受傷害轉移給隨機召喚物'],
  ['Shadow Quantity +1', '暗影數量 +1'],
  ['Weaken nearby enemies when triggering any skill', '施放任意技能時弱化附近敵人'],
  ['restore 15% of Life, Energy Shield, and Mana when Blocking', '格擋時回復 15% 生命、能量護盾與魔力'],
  ['inflict 1 additional stack(s) of Deterioration', '額外施加 1 層惡化'],
  ['inflict 1 additional stack(s) of Wilt', '額外施加 1 層枯萎'],
  ['Erosion Damage per stack of Wilt inflicted, stacking up to 60 times', '每層枯萎造成之腐蝕傷害，最多疊加 60 次'],
  ['Elemental Resistance per 3000 Armor. Stacks up to 6%', '每 3000 護甲之元素抗性，最多 6%'],
  ['Erosion Resistance per 3000 Armor. Stacks up to 6%', '每 3000 護甲之腐蝕抗性，最多 6%'],
  ['Critical Strike Damage per Fervor Rating', '每狂熱值之暴擊傷害'],
  ['Attack Speed for every 1% of Life lost', '每失去 1% 生命之攻擊速度'],
  ['Movement Speed for each activated Tangle', '每個已啟動纏繞之移動速度'],
  ['bonuses for Movement Speed is also applied to the Cooldown Recovery Speed of Mobility skills', '移動速度加成同時套用於位移技能冷卻回復速度'],
  ['bonuses for Movement Speed is also applied to the Attack and Cast Speed of Mobility Skills', '移動速度加成同時套用於位移技能攻擊與施法速度'],
  ['increase/decrease on Knockback distance is also applied to damage bonus', '擊退距離增減同時套用於傷害加成'],
  ['Attack Critical Strike Rating when holding a Two-Handed Weapon', '持雙手武器時攻擊暴擊值'],
  ['Spell Critical Strike Damage', '法術暴擊傷害'],
  ['Energy Shield Regain Interval', '能量護盾回復間隔'],
  ['Mobility Skills', '位移技能'],
  ['Two-Handed Weapon', '雙手武器'],
  ['One-Handed Weapon', '單手武器'],
  ['Dual Wielding', '雙持'],
  ['crowd control effects', '控場效果'],
  ['Synthetic Troop Skill', '合成部隊技能'],
  ['Synthetic Troop', '合成部隊'],
  ['Spirit Magus', '魔導精靈'],
  ['Tenacity Blessing', '堅韌祝福'],
  ['Agility Blessing', '敏捷祝福'],
  ['Focus Blessing', '專注祝福'],
  ['Frostbitten enemies', '霜凍敵人'],
  ['Frostbitten enemy', '霜凍敵人'],
  ['Frostbitten', '霜凍'],
  ['Frozen enemies', '冰封敵人'],
  ['Low Life enemies', '低血敵人'],
  ['Cursed enemies', '受詛咒敵人'],
  ['Nearby enemies', '附近敵人'],
  ['Distant enemies', '遠方敵人'],
  ['enemies in proximity', '近距離內敵人'],
  ['enemies affected by Ailments', '受異常狀態影響的敵人'],
  ['Blinded enemies', '致盲敵人'],
  ['Ignited enemies', '燃燒敵人'],
  ['Warcry Skill', '戰吼技能'],
  ['Warcry', '戰吼'],
  ['Mobility skill', '位移技能'],
  ['Mobility Skills', '位移技能'],
  ['Main Skill', '主技能'],
  ['Ultimate', '終極技能'],
  ['Enhanced Skill', '強化技能'],
  ['Triggered Skills', '觸發技能'],
  ['Multistrike', '多重打擊'],
  ['Multistrikes', '多重打擊'],
  ['Regained', '回復'],
  ['Shield Regain', '護盾回復'],
  ['Life Regain', '生命回復'],
  ['Blocked', '格擋'],
  ['Blocking', '格擋'],
  ['defeat', '擊敗'],
  ['on defeat', '擊敗時'],
  ['on hit', '命中時'],
  ['on Critical Strike', '暴擊時'],
  ['per second', '每秒'],
  ['recently', '近期'],
  ['in the last 8s', '過去 8 秒內'],
  ['in the last 1 s', '過去 1 秒內'],
  ['in the last 2 s', '過去 2 秒內'],
  ['if you have', '若擁有'],
  ['when having', '擁有時'],
  ['when holding', '持有時'],
  ['while holding', '持有時'],
  ['while Dual Wielding', '雙持時'],
  ['while standing still', '靜止時'],
  ['while moving', '移動時'],
  ['while at Full Mana', '滿魔時'],
  ['while Agility Blessing is active', '敏捷祝福生效時'],
  ['when Focus Blessing is active', '專注祝福生效時'],
  ['when Tenacity Blessing is active', '堅韌祝福生效時'],
  ['when channeled stacks have not reached cap', '引導層數未達上限時'],
  ['upon inflicting damage', '造成傷害時'],
  ['against', '對'],
  ['enemies', '敵人'],
  ['enemy', '敵人'],
  ['additional ', '額外'],
  ['Additional ', '額外'],
  ['chance to ', '機率'],
  ['Chance to ', '機率'],

  // 整行或長條件（避免片語拆壞語序）
  ['+3% Attack and Cast Speed for Channeled Skills', '+3% 引導技能之攻擊與施法速度'],
  [
    '-5% additional Elemental Damage taken for every type of Elemental Damage recently received',
    '近期每受到一種元素傷害類型，額外所受元素傷害 -5%',
  ],
  ['+8% Armor DMG Mitigation Penetration', '+8% 護甲傷害減免穿透'],
  ['+40% additional Beam Length', '+40% 額外光束長度'],
  ['0.2% Blur effect for every 1% of Life lost', '每失去 1% 生命，飄忽效果 +0.2%'],
  ['-80% additional damage taken by Spirit Magi', '魔導精靈所受額外傷害 -80%'],
  ['+20% Sentry Damage', '+20% 哨衛傷害'],
  ['+8% Sentry Damage', '+8% 哨衛傷害'],
  ['+8% Barrier Absorption Rate', '+8% 屏障吸收速率'],
  ['Armor DMG Mitigation Penetration', '護甲傷害減免穿透'],
  ['Barrier Absorption Rate', '屏障吸收速率'],
  ['Beam Length', '光束長度'],
  ['Block Ratio', '格擋率'],
  ['Melee Damage', '近戰傷害'],
  ['Minion Erosion Damage', '召喚物腐蝕傷害'],
  ['Spirit Magi', '魔導精靈'],
]
